package com.decisiondesk.backend.meetings.model;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Transcript generated by Whisper for a meeting.
 */
public record Transcript(UUID id, UUID meetingId, String language, String text, OffsetDateTime createdAt) {
}
